tag-name = "v{{version}}"
tag-message = "Release v{{version}}"
allow-branch = ["main"]
push-remote = "origin"
consolidate-commits = true
sign-commit = false
sign-tag = false
publish = false
verify = true
push = true


