name: release-on-tag

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      artifact: vps-audit-linux-x86_64
                    - target: aarch64-unknown-linux-gnu
                      artifact: vps-audit-linux-aarch64
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Install cross toolchain (aarch64)
              if: matrix.target == 'aarch64-unknown-linux-gnu'
              run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

            - name: Build
              env:
                  CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
              run: |
                  cargo build --release --target ${{ matrix.target }}
                  mkdir -p dist/${{ matrix.target }}
                  cp target/${{ matrix.target }}/release/vps-audit dist/${{ matrix.target }}/${{ matrix.artifact }}
                  chmod +x dist/${{ matrix.target }}/${{ matrix.artifact }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact }}
                  path: dist/${{ matrix.target }}/${{ matrix.artifact }}

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: dist
                  merge-multiple: true

            - name: Create GitHub Release and upload assets
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/*
                  draft: false
                  prerelease: false
