name: release-on-tag

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      artifact: vps-audit-linux-x86_64
                    - target: aarch64-unknown-linux-gnu
                      artifact: vps-audit-linux-aarch64
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Install cross toolchain (aarch64)
              if: matrix.target == 'aarch64-unknown-linux-gnu'
              run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

            - name: Build
              env:
                  CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
              run: |
                  cargo build --release --target ${{ matrix.target }}
                  mkdir -p dist
                  cp target/${{ matrix.target }}/release/vps-audit dist/${{ matrix.artifact }}
                  chmod +x dist/${{ matrix.artifact }}

            - name: Create GitHub Release and upload asset
              uses: softprops/action-gh-release@v2
              permissions:
                  contents: write
              with:
                  files: |
                      dist/${{ matrix.artifact }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
