name: build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload artifact (linux x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: vps-audit-linux-x86_64
          path: target/release/vps-audit


